### PR TITLE
Add statistics.alpha.canada.ca / statistiques.alpha.canada.ca CNAME record

### PR DESCRIPTION
**Pull request by zachomedia**
We are experimenting with running the main Statistics Canada website in our Kubernetes environment in the cloud.

cc @sinkinsona @sylus

### CODE REVIEW

**Comment by sylus** [comment]
hey @dsamojlenko anychance could poke you to take a look at this :D

**Comment by obrien-j** [comment]
Sorry @sylus , looks like we don't have auto-assign setup on the repo. Just tagging in @maxneuvians as I know we're still sorting out the outside collab PR's + CI test run issue.

**Comment by zachomedia** [comment]
@maxneuvians Is it possible to get this reviewed? We would like to start settings this up shortly. Thanks in advance!

**Comment by maxneuvians** [comment]
@zachomedia Re-adding it here for https://github.com/cds-snc/dns/pull/82, CI does not work on external PRs :(

**Comment by maxneuvians** [comment]
Closing because merged in #82

**Comment by zachomedia** [comment]
Thank you @maxneuvians!

**Pull request closed without merging**
