### PR TITLE
Added gcperformance.alpha.canada.ca

### PR DESCRIPTION
**Pull request by kfletche-tbs**
Hi Folks! Fingers crossed you would be kind enough to add gcperformance to your alpha roster. If there are any questions/comments/concerns, please do not hesitate to email/teams at kyle.fletcher@tbs-sct.gc.ca

### CODE REVIEW

**Comment by patheard** [comment]
👋🏻 just a quick question before going ahead - do you have a service up and running for that domain?  

We're being cautious about granting subdomain delegation without a running service because there have been a lot of dangling record takeover attacks showing up on `*.canada.ca` domains.

Let me know!

**Comment by kfletche-tbs** [comment]
UNCLASSIFIED / NON CLASSIFIÉ

Yes sir! gcperformance.alpha.canada.ca is setup in azure as a dns zone 😊. Should have at least a web service running on there as of Monday as well ! Thanks again for the help!

**Comment by patheard** [comment]
Ah great to hear - ping me once you've got the web service up and running and I'll get this taken care of right away!

**Comment by kfletche-tbs** [comment]
UNCLASSIFIED / NON CLASSIFIÉ

Just sent an email but might have guessed your address wrong.  Have a wildcard cname on there pointing to a static app service now 😊

**Comment by kfletche-tbs** [comment]
Stopped replying to comments by email :-)  Have a couple extra TXT records in there for verification as well so ready when you are when you get a chance.  Thanks again for the help.

**Comment by patheard** [comment]
Perfect, thanks for letting me know.  I've got #418 open to take care of getting this added just because of limitations in how our Terraform workflows are currently setup (they don't currently work well with forked PRs).

**Comment by kfletche-tbs** [comment]
Works for me. Thanks again.

**Comment by patheard** [comment]
The NS record has been created - let us know if you need anything else!
```
❯ dig NS gcperformance.alpha.canada.ca

; <<>> DiG 9.10.6 <<>> NS gcperformance.alpha.canada.ca
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4375
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1220
;; QUESTION SECTION:
;gcperformance.alpha.canada.ca.	IN	NS

;; ANSWER SECTION:
gcperformance.alpha.canada.ca. 281 IN	NS	ns3-04.azure-dns.org.
gcperformance.alpha.canada.ca. 281 IN	NS	ns1-04.azure-dns.com.
gcperformance.alpha.canada.ca. 281 IN	NS	ns2-04.azure-dns.net.
gcperformance.alpha.canada.ca. 281 IN	NS	ns4-04.azure-dns.info.
```

**Pull request closed without merging**
