### PR TITLE
fix(statcan-alpha): fix typo with acme-challenge prefix.

### PR DESCRIPTION
**Pull request by justbert**
# Summary | Résumé

A quick typo fix.

### CODE REVIEW

**Comment by justbert** [comment]
Hey @CalvinRodo ! I found a typo in our configs. :\ Can you merge this is? Thanks!

**Review by CalvinRodo — APPROVED** [review]
Change looks fine to me

**Comment by CalvinRodo** [comment]
Because I still haven't fixed DNS repo IAM users will have to do a seperate PR again

**Comment by justbert** [comment]
Thanks!

**Pull request closed without merging**
