### PR TITLE
feat: upgrade Terraform to 0.13

### LINKED ISSUE #131: Update Terraform to v0.13
We should update to the latest version of TF as there are some breaking changes between our TF and the latest version. 

Useful Docs for this task: 
https://www.terraform.io/upgrade-guides/0-13.html

And Providers are handled differently in TF as of v0.13 please see the following: 
https://www.terraform.io/docs/configuration/provider-requirements.html#best-practices-for-provider-versions

### PR DESCRIPTION
**Pull request by AntoineAugusti**
Fixes #131

- Bump Terraform to 0.13
- Change how the AWS provider is declared
- Fix warnings
- `fmt` all the files

### CODE REVIEW

**Comment by maxneuvians** [comment]
Screen Shot 2021-01-28 at 3 34 43 PM

**Review by maxneuvians — APPROVED** [review]
LGTM

**Comment by maxneuvians** [comment]
Let us get @CalvinRodo to look at it as well

**Review by CalvinRodo — APPROVED** [review]
So ideally I would like to have such a large amount of formatting happen in it's own PR as it makes it harder to review the real changes here. 

However it looks good to me so I won't quibble too much. 

As for state issues they are when migration from v2.x of the AWS Provider to v3.x of the provider. 

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade#resource-aws_acm_certificate

So we will need to be aware of this if we upgrade to v3. 

Which I imagine we will have to do at some point.

**Comment by AntoineAugusti** [comment]
@CalvinRodo Made sure to split commits and keep a meaningful history in this PR, sorry you felt like the `fmt` would have been better in another PR - will keep that in mind.

My plan was to tackle after #132 after this one so I'll keep your comment in mind, thanks!

**Comment by CalvinRodo** [comment]
> @CalvinRodo Made sure to split commits (commits 1 and 2 are the real deal) and keep a meaningful history in this PR, sorry you felt like the `fmt` would have been better in another PR - will keep that in mind.
> 
> My plan was to tackle after #132 after this one so I'll keep your comment in mind, thanks!

No worries appreciate that, I didn't notice due to the way github UI works on prs by grouping all changes together.

**Pull request merged**
