### PR TITLE
chore: update statcan cname for energy-information

### PR DESCRIPTION
**Pull request by CalvinRodo**
# Summary | Résumé

Read this PR: https://github.com/cds-snc/dns/pull/184

Recreating this so secrets are run.

### CODE REVIEW

**Comment by CalvinRodo** [comment]
@zachomedia please confirm this is still correct.

**Review by mohamed-cds — APPROVED** [review]
Matches the other PR. LGTM 🚀 ✅

**Review by wanpeng-cds — APPROVED** [review]
🚀 LGTM

**Comment by zachomedia** [comment]
@CalvinRodo Thanks, I can confirm that this is correct!

**Pull request merged**
