### PR TITLE
feat(dns): Add DNS domain for gccloudone alpha initiative

### PR DESCRIPTION
**Pull request by sylus**
# Summary | Résumé

Adding DNS records for gccloudone initiative at SSC.

### CODE REVIEW

**Comment by sylus** [comment]
Hey @patheard I know your busy if were able to any change getting this actioned by tomorrow?

I would owe you yet again :)

**Review by sylviamclaughlin — APPROVED** [review]

**Comment by sylus** [comment]
Thanks @sylviamclaughlin let me know if need anything to aid in your review :)

**Comment by sylviamclaughlin** [comment]
> Thanks @sylviamclaughlin let me know if need anything to aid in your review :)

Hi @sylus,
Pat is away today, but I have cloned this into #423. Let me know if it looks good to you and then I can merge it.

**Comment by sylus** [comment]
Hi @sylviamclaughlin 

Looks perfect to me :) Thank you so much!!!

**Comment by sylviamclaughlin** [comment]
> Hi @sylviamclaughlin
> 
> Looks perfect to me :) Thank you so much!!!

@sylus - you should be good to go now:
```
dig gccloudone.alpha.canada.ca +short
gccloudone.github.io.
185.199.109.153
185.199.108.153
185.199.111.153
185.199.110.153
```
```
dig aurora.gccloudone.alpha.canada.ca +short
gccloudone.github.io.
185.199.110.153
185.199.111.153
185.199.109.153
185.199.108.153
```

**Comment by sylus** [comment]
Thank you so much @sylviamclaughlin !!!

**Pull request closed without merging**
